// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.1
// source: src/proto/message.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "";

export enum FileEvent {
  /** EVENT_RECEIVER_ACCEPT - event when the reveiver got metadata and accepted the file */
  EVENT_RECEIVER_ACCEPT = 0,
  /** EVENT_RECEIVER_REJECT - event when the reveiver rejected the file */
  EVENT_RECEIVER_REJECT = 1,
  /** EVENT_VALIDATE_ERROR - event when the reveiver got validate error */
  EVENT_VALIDATE_ERROR = 2,
  UNRECOGNIZED = -1,
}

export function fileEventFromJSON(object: any): FileEvent {
  switch (object) {
    case 0:
    case "EVENT_RECEIVER_ACCEPT":
      return FileEvent.EVENT_RECEIVER_ACCEPT;
    case 1:
    case "EVENT_RECEIVER_REJECT":
      return FileEvent.EVENT_RECEIVER_REJECT;
    case 2:
    case "EVENT_VALIDATE_ERROR":
      return FileEvent.EVENT_VALIDATE_ERROR;
    case -1:
    case "UNRECOGNIZED":
    default:
      return FileEvent.UNRECOGNIZED;
  }
}

export function fileEventToJSON(object: FileEvent): string {
  switch (object) {
    case FileEvent.EVENT_RECEIVER_ACCEPT:
      return "EVENT_RECEIVER_ACCEPT";
    case FileEvent.EVENT_RECEIVER_REJECT:
      return "EVENT_RECEIVER_REJECT";
    case FileEvent.EVENT_VALIDATE_ERROR:
      return "EVENT_VALIDATE_ERROR";
    case FileEvent.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum FilePartEvent {
  /** EVENT_RECEIVED_CHUNK - event when the receiver got file part chunk */
  EVENT_RECEIVED_CHUNK = 0,
  /** EVENT_RECEIVED_FILE_PART_METADATA - event when the receiver get the file part metadata */
  EVENT_RECEIVED_FILE_PART_METADATA = 1,
  UNRECOGNIZED = -1,
}

export function filePartEventFromJSON(object: any): FilePartEvent {
  switch (object) {
    case 0:
    case "EVENT_RECEIVED_CHUNK":
      return FilePartEvent.EVENT_RECEIVED_CHUNK;
    case 1:
    case "EVENT_RECEIVED_FILE_PART_METADATA":
      return FilePartEvent.EVENT_RECEIVED_FILE_PART_METADATA;
    case -1:
    case "UNRECOGNIZED":
    default:
      return FilePartEvent.UNRECOGNIZED;
  }
}

export function filePartEventToJSON(object: FilePartEvent): string {
  switch (object) {
    case FilePartEvent.EVENT_RECEIVED_CHUNK:
      return "EVENT_RECEIVED_CHUNK";
    case FilePartEvent.EVENT_RECEIVED_FILE_PART_METADATA:
      return "EVENT_RECEIVED_FILE_PART_METADATA";
    case FilePartEvent.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface FilePartMetaData {
  /** file part number */
  partNumber: number;
  /** size of this part in bytes */
  partSize: number;
}

export interface FileMetadata {
  /** file name */
  name: string;
  /** total size of the file in bytes */
  size: number;
  /** mime type */
  type: string;
  /** is the file part encrypted */
  isEncrypt: boolean;
  /** number of channels used to send this part */
  channels: number;
  /** encrypted AES key */
  key?: Uint8Array | undefined;
}

export interface Message {
  /** file id */
  id: string;
  fileMetadata?:
    | FileMetadata
    | undefined;
  /** use for sender to send file metadata */
  filePartMetaData?:
    | FilePartMetaData
    | undefined;
  /** file part chunk data */
  chunk?:
    | Uint8Array
    | undefined;
  /** response event for file, receiver will tell the sender file status */
  fileEvent?:
    | FileEvent
    | undefined;
  /** response event for file part, receiver will tell the sender file part status */
  filePartEvent?: FilePartEvent | undefined;
}

function createBaseFilePartMetaData(): FilePartMetaData {
  return { partNumber: 0, partSize: 0 };
}

export const FilePartMetaData: MessageFns<FilePartMetaData> = {
  encode(message: FilePartMetaData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.partNumber !== 0) {
      writer.uint32(48).int32(message.partNumber);
    }
    if (message.partSize !== 0) {
      writer.uint32(56).int32(message.partSize);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FilePartMetaData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFilePartMetaData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.partNumber = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.partSize = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FilePartMetaData {
    return {
      partNumber: isSet(object.partNumber) ? globalThis.Number(object.partNumber) : 0,
      partSize: isSet(object.partSize) ? globalThis.Number(object.partSize) : 0,
    };
  },

  toJSON(message: FilePartMetaData): unknown {
    const obj: any = {};
    if (message.partNumber !== 0) {
      obj.partNumber = Math.round(message.partNumber);
    }
    if (message.partSize !== 0) {
      obj.partSize = Math.round(message.partSize);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FilePartMetaData>, I>>(base?: I): FilePartMetaData {
    return FilePartMetaData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FilePartMetaData>, I>>(object: I): FilePartMetaData {
    const message = createBaseFilePartMetaData();
    message.partNumber = object.partNumber ?? 0;
    message.partSize = object.partSize ?? 0;
    return message;
  },
};

function createBaseFileMetadata(): FileMetadata {
  return { name: "", size: 0, type: "", isEncrypt: false, channels: 0, key: undefined };
}

export const FileMetadata: MessageFns<FileMetadata> = {
  encode(message: FileMetadata, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.size !== 0) {
      writer.uint32(16).int32(message.size);
    }
    if (message.type !== "") {
      writer.uint32(26).string(message.type);
    }
    if (message.isEncrypt !== false) {
      writer.uint32(32).bool(message.isEncrypt);
    }
    if (message.channels !== 0) {
      writer.uint32(40).int32(message.channels);
    }
    if (message.key !== undefined) {
      writer.uint32(66).bytes(message.key);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FileMetadata {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFileMetadata();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.size = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.isEncrypt = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.channels = reader.int32();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.key = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FileMetadata {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      size: isSet(object.size) ? globalThis.Number(object.size) : 0,
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      isEncrypt: isSet(object.isEncrypt) ? globalThis.Boolean(object.isEncrypt) : false,
      channels: isSet(object.channels) ? globalThis.Number(object.channels) : 0,
      key: isSet(object.key) ? bytesFromBase64(object.key) : undefined,
    };
  },

  toJSON(message: FileMetadata): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.size !== 0) {
      obj.size = Math.round(message.size);
    }
    if (message.type !== "") {
      obj.type = message.type;
    }
    if (message.isEncrypt !== false) {
      obj.isEncrypt = message.isEncrypt;
    }
    if (message.channels !== 0) {
      obj.channels = Math.round(message.channels);
    }
    if (message.key !== undefined) {
      obj.key = base64FromBytes(message.key);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FileMetadata>, I>>(base?: I): FileMetadata {
    return FileMetadata.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FileMetadata>, I>>(object: I): FileMetadata {
    const message = createBaseFileMetadata();
    message.name = object.name ?? "";
    message.size = object.size ?? 0;
    message.type = object.type ?? "";
    message.isEncrypt = object.isEncrypt ?? false;
    message.channels = object.channels ?? 0;
    message.key = object.key ?? undefined;
    return message;
  },
};

function createBaseMessage(): Message {
  return {
    id: "",
    fileMetadata: undefined,
    filePartMetaData: undefined,
    chunk: undefined,
    fileEvent: undefined,
    filePartEvent: undefined,
  };
}

export const Message: MessageFns<Message> = {
  encode(message: Message, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.fileMetadata !== undefined) {
      FileMetadata.encode(message.fileMetadata, writer.uint32(18).fork()).join();
    }
    if (message.filePartMetaData !== undefined) {
      FilePartMetaData.encode(message.filePartMetaData, writer.uint32(26).fork()).join();
    }
    if (message.chunk !== undefined) {
      writer.uint32(34).bytes(message.chunk);
    }
    if (message.fileEvent !== undefined) {
      writer.uint32(40).int32(message.fileEvent);
    }
    if (message.filePartEvent !== undefined) {
      writer.uint32(48).int32(message.filePartEvent);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Message {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.fileMetadata = FileMetadata.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.filePartMetaData = FilePartMetaData.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.chunk = reader.bytes();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.fileEvent = reader.int32() as any;
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.filePartEvent = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Message {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      fileMetadata: isSet(object.fileMetadata) ? FileMetadata.fromJSON(object.fileMetadata) : undefined,
      filePartMetaData: isSet(object.filePartMetaData) ? FilePartMetaData.fromJSON(object.filePartMetaData) : undefined,
      chunk: isSet(object.chunk) ? bytesFromBase64(object.chunk) : undefined,
      fileEvent: isSet(object.fileEvent) ? fileEventFromJSON(object.fileEvent) : undefined,
      filePartEvent: isSet(object.filePartEvent) ? filePartEventFromJSON(object.filePartEvent) : undefined,
    };
  },

  toJSON(message: Message): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.fileMetadata !== undefined) {
      obj.fileMetadata = FileMetadata.toJSON(message.fileMetadata);
    }
    if (message.filePartMetaData !== undefined) {
      obj.filePartMetaData = FilePartMetaData.toJSON(message.filePartMetaData);
    }
    if (message.chunk !== undefined) {
      obj.chunk = base64FromBytes(message.chunk);
    }
    if (message.fileEvent !== undefined) {
      obj.fileEvent = fileEventToJSON(message.fileEvent);
    }
    if (message.filePartEvent !== undefined) {
      obj.filePartEvent = filePartEventToJSON(message.filePartEvent);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Message>, I>>(base?: I): Message {
    return Message.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Message>, I>>(object: I): Message {
    const message = createBaseMessage();
    message.id = object.id ?? "";
    message.fileMetadata = (object.fileMetadata !== undefined && object.fileMetadata !== null)
      ? FileMetadata.fromPartial(object.fileMetadata)
      : undefined;
    message.filePartMetaData = (object.filePartMetaData !== undefined && object.filePartMetaData !== null)
      ? FilePartMetaData.fromPartial(object.filePartMetaData)
      : undefined;
    message.chunk = object.chunk ?? undefined;
    message.fileEvent = object.fileEvent ?? undefined;
    message.filePartEvent = object.filePartEvent ?? undefined;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
